[package]
name = "test-tx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
argh = "0.1.12"
ethers = { workspace = true, features = ["optimism"] }
tracing-subscriber.workspace = true
rpassword = "7.3.1"
tokio.workspace = true
tracing.workspace = true
lib-didethresolver = { path = "../../lib" }
base64 = "0.21"
hex = "0.4.3"

