name: Build Prod Image CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Prod Image CI
        uses: docker/build-push-action@v3
        with:
          context: .
          file: prod/Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            VERSION=latest
            CARGO_INCREMENTAL=0
